---
title: "Case Study 1"
author: "Michael Daniel Bigler and Liam Arthur Phan"
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    code_folding: hide
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	include = TRUE,
	fig.align = "center")
rm(list = ls())
cat("\014")

```

# Packages

```{r packages}

library(ggplot2)
library(DT)

```

# Exercise 1

## Dataset

```{r load data}

df_original <- read.csv('Case_Study_1.csv')
datatable(df_original)

df_log <- df_original
df <- df_original

```

## Scatterplot

```{r Scatter plot}

A <- df$manufacturing_cost[1]
#A <- 2772.258
b <- mean((log(df$manufacturing_cost)-log(A))/log(df$number_of_solar_panels))
#b <- -0.1730591

experience_curve <- function(X, A, b){
  Y <- A*X^b
  return(Y)
}

df$Y_func <- experience_curve(df$number_of_solar_panels, A, b)
  
Plot1 <- ggplot(df, aes(x=number_of_solar_panels, y=manufacturing_cost)) + geom_point(color="#32A287") + theme_minimal() + labs(title = "Experience Curve",subtitle = "Scatterplot", x="Solar Pannels", y="Manufacturing Cost", caption = "Case Study 1") + geom_line(aes(y=Y_func), colour="#F0C987", size=1)

Plot1

```

## Formula

$$
Y = AX^b
$$

> We want a linear relationship, thus log transformation:

$$
\log(Y) = \log(A) + b*\log(X)
$$

## Data Log Transformation

```{r Data Transformation}

df_log$number_of_solar_panels <- log(df_log$number_of_solar_panels)
df_log$manufacturing_cost <- log(df_log$manufacturing_cost)

```

## Scatterplot Log

```{r Scatter plot Log}

A_log <- df_log$manufacturing_cost[1]

Plot2 <- ggplot(df_log, aes(x=number_of_solar_panels, y=manufacturing_cost)) + geom_point(color="#32A287") + theme_minimal() + labs(title = "Experience Curve - Log Data",subtitle = "Scatterplot", x="log(Number of Solar Pannels)", y="log(Manufacturing Cost)", caption = "Case Study 1")

Plot2

```

# Exercise 2

## Log Linear Regression

```{r Estimates}

fit_1 <- lm(I(df_log$number_of_solar_panels - A_log) ~ 0 + df_log$manufacturing_cost, df_log)

b_log <- fit_1$coefficients

summary(fit_1)


```

## Scatterplot and Regression

```{r Log-Linear Regression}

Plot2 <- ggplot(df_log, aes(x=number_of_solar_panels, y=manufacturing_cost)) + geom_point(color="#32A287") + theme_minimal() + labs(title = "Experience Curve - Log Data",subtitle = "Scatterplot", x="log(Number of Solar Pannels)", y="log(Manufacturing Cost)", caption = "Case Study 1") + geom_abline(intercept = A_log, slope = b_log, color="#F0C987", size=1) 

Plot2

```

```{r Free Intercept Estimates}

fit_2 <- lm(df_log$manufacturing_cost  ~ ., df_log)

intercept_log_2 <- fit_2$coefficients[1]
b_log_2 <- fit_2$coefficients[2]

summary(fit_2)

```

```{r Log-Linear Regression 2}

Plot3 <- ggplot(df_log, aes(x=number_of_solar_panels, y=manufacturing_cost)) + geom_point(color="#32A287") + theme_minimal() + labs(title = "Experience Curve - Log Data",subtitle = "Scatterplot", x="log(Number of Solar Pannels)", y="log(Manufacturing Cost)", caption = "Case Study 1") + geom_abline(intercept = intercept_log_2, slope = b_log_2, color="#F0C987", size=1) 

Plot3


```

## Learning Rate

$$
b = Slope \: Coefficient = log(learning\: rate)/log_2 
$$

$$
Slope \: of \: the \: experience \: rate = 2^b
$$

```{r Learning Rate}


Learning_Rate <- 2^(b_log)


```

# Exercise 3

## Predict Future Prices

```{r Predict}

values <- seq(2200, 5000, 100)

targets <- data.frame(number_of_solar_panels = values)

targets$number_of_solar_panels <- log(targets$number_of_solar_panels)

predictions <- predict.lm(fit_2, newdata = targets)

predictions_final <- exp(predictions)

PREDICTIONS <- data.frame(values, predictions_final)

colnames(PREDICTIONS)[1] ="number_of_solar_panels"
colnames(PREDICTIONS)[2] ="manufacturing_cost"


PREDICTIONS_FINAL <- rbind(df_original,PREDICTIONS)

Plot3 <- ggplot(PREDICTIONS_FINAL, aes(x=number_of_solar_panels, y=manufacturing_cost)) + geom_point(color="#32A287") + theme_minimal() + labs(title = "Experience Curve",subtitle = "Predictinos", x="Number of Solar Pannels", y="Manufacturing Cost", caption = "Case Study 1") + geom_vline(xintercept = 2300, color="#F0C987")

Plot3


```

## Mean of Predictions

```{r Mean Of Predictions}

Targets_1 <- c(4700, 4800, 4900, 5000)

Targets_Costs <- PREDICTIONS_FINAL$manufacturing_cost[PREDICTIONS_FINAL$number_of_solar_panels %in% Targets_1]

Target_Mean <- mean(Targets_Costs)

Target_Mean

```

# Exercise 4
